### ISSUE TITLE
HTMLAudioPlugin.TagPool Logic & Doc Comment

### ISSUE THREAD

**Issue by pittins** [CreateJS/SoundJS#124]
### Part 1: tags[a] is undefined
I noticed this error in Firefox, looked into it, realized it didn't really mean anything, and removed the error prompt with a simple `if(this.tags.length==0)return;` line in `TagPool.prototype.checkSrcChange()`. Looks like TagPool and other sound-related code is undergoing major modifications in the NEXT release, so I'm not worrying about it nor am I complaining about it. `p.checkSrcChange()` isn't even in NEXT anymore, so this error would be gone in the next release most likely.

### Part 2: TagPool.prototype.length and TagPool.prototype.available
I got onto this train of thought while looking into the whole `this.tags[a] is undefined` error in Firefox thing. It seems like TagPool is used only internally by SoundJS, but even still I'm thinking that some naming convention or documentation updates might be in order for these two variables. Note that I'm referencing both NEXT and 0.5.2 in this section.

##### this.length
From a quick glance at the code of TagPool, it appears that `this.length` is really just a reference to "the maximum size of the TagPool", without regard to which tags are still inside the pool or have been taken from it. So long of course, as `p.add()` is only used to "initialize" the pool and `p.get()` and `p.set()` are only used to take-and-return tags from the pool as needed.

Pretty straightforward, but `this.maxSize` might be a more appropriate name for this property: The "length" of the pool changes as tags are retrieved-and-returned, but the maximum size of the pool would not change unless new tag elements are added to it. Maybe this is just me though, as I hear "pool size" more frequently than I hear "pool length".

##### this.available
Now the variable `this.available` is quite curious. A naive assumption would be that `this.available` is just a reference to the length of the `this.tags` array, and just refers to "how many tags are currently available in the pool". Unfortunately this does not hold entirely true. While `p.add()` does what it is supposed to do and increments the `this.available` counter for each tag added to the pool, the immediate next method `p.removeAll()` fails to "reset" the value (however it does reset `this.length`). It could be that this is not important if the TagPool is never reused, but if they are reusable then `this.available` should be reset in either the `p._init()` or `p.removeAll()` methods. Again, this might not be a problem depending on how TagPool is used.

`p.get()` also seems to incorrectly modify the value of `this.available`. After the method call, `this.available==this.tags.length+1` due to it `.pop()`'ing the tag after setting the value. But after the method call to `p.set()`, `this.available==this.tags.length` exactly. Shouldn't both methods result in the same state of `this.available==this.tags.length` after execution?

It seems to me like the number of "available" tags in the pool could just be a function like `p.countOfAvailableTags()` that just returns `this.tags.length` or zero if uninitialized, as that is *almost* what the variable is currently trying to do.

### Conclusion
Anyways, minor nitpicks, but to me it just appears to be a bit inconsistent, and it caught my eye when looking into the whole `tags[a]` thing before I realized it actually works fine. And say what you will about my opinion on renaming `this.length` to `this.maxSize`, but `this.available` does seem to return an incorrect value after calls to `p.get()`.

**Comment by OJayRobinson** [comment]
Resolving issue [152](https://github.com/CreateJS/SoundJS/issues/152) has also resolve this, as the refactor removed the code related to your issues.  If you'd like to take another look, I'd be interested in what you think.  Thanks.
