### ISSUE TITLE
IE10 (Aborted) status

### ISSUE THREAD

**Issue by tehmaestro** [CreateJS/SoundJS#139]
Hi. I'm using SoundJS preloading like this :  

```javascript```
createjs.Sound.registerSounds(audio)
```

Both the `fileerror` and `fileload` events work as expected in all other browsers, except for Internet Explorer. In IE10, when the audio file doesn't exist, so a 404 error is returned, the browser actually changes the request to a (Aborted) status.

How can I catch the (Aborted) status? How can I treat this case, so I know what's happening with each of my files that I'm loading.

  Thanks.

PS: I have no idea why I'm not getting just regular 404 errors. The files don't exist, so I would expect to get a 404, and let the fileerror event handle it.

**Comment by OJayRobinson** [comment]
Hmm, that's an interesting issue.  Currently SoundJS does not handle aborted files, but does handle stalled ones.  There was a bug in the last release that the HTMLAudioPlugin did not handle stalled files correctly, with a fix pushed to the [git repo](https://github.com/CreateJS/SoundJS) as SoundJS-Next.  Can you try the latest version and let me know if that resolves your issues?

Hope that helps.

**Comment by OJayRobinson** [comment]
Investigation found HTMLAudio loading was not capturing the error event from the audio tag, which would show this error for all HTMLAudioPlugin usage.  All other browsers currently default to WebAudioPlugin, which is likely why you only saw the issue in ie.

A fix has been pushed to SoundJS-NEXT.

Hope that helps.
