### ISSUE TITLE
IE8 and FlashAudioPlugin - Object doesn't support this property or method this.AbstractPlugin_constructor();

### ISSUE THREAD

**Issue by mozzi** [CreateJS/SoundJS#142]
Trying to use FlashAudioPlugin as fallback for IE8, but got following error:
Object doesn't support this property or method  flashaudioplugin-0.6.0.combined.js?body=1, line 1180 character 3

```javascript
function FlashAudioPlugin() {
		this.AbstractPlugin_constructor();
```

Any ideas how to fix it?

**Comment by OJayRobinson** [comment]
huh, thats no good.
Thanks for bringing this to our attention, I'll take a look into it and let you know when I have a solution.

**Comment by lannymcnie** [comment]
This issue is related to the new inheritance model that does not play nicely with IE8 (affects preload, tween, and sound). We are looking at solutions already. In the mean time, I suggest using Preload v 0.4.1.

Cheers

**Comment by lannymcnie** [comment]
This is not going to be addressed moving forward. For projects that require IE8 fallback, please use version 0.5.2, which fully supports IE8.
