### ISSUE TITLE
SoundJS (v0.6.0) - PreloadJS (v0.6.0) integration regression

### ISSUE THREAD

**Issue by Omer** [CreateJS/SoundJS#143]
In a nutshell, the issue I am experiencing is the following, unloading a sound file using PreloadJS' (v0.6.0) LoadQueue#remove is attempting to destroy the appropriate loader by delegating to SoundJS' (v0.6.0) AbstractLoader#clean/AbstractLoader#destroy. Sadly, this does not actually discard the loader from the AbstractLoader#_loaders cache which results in two things. First, memory leak by keeping reference to unusable loaders. Second, any future attempt to re-load this sound will result in a "broken" (i.e., previously destroyed) loader being returned (through AbstractPlugin#register).

This regression in the integration between SoundJS and PreloadJS did not exist in the previous versions of these libraries. As example can be found at:

http://jsfiddle.net/7mmwdres/   : soundjs-0.5.2 / preloadjs-0.4.1
http://jsfiddle.net/7mmwdres/1/ : soundjs-0.6.0 / preloadjs-0.6.0

The stacktrace I am receiving when trying to reload a previously discarded sound is:

    Uncaught TypeError: Cannot read property 'type' of null
    b._canStartLoad
    b._loadNext
    b.setPaused
    b.loadFile

**Comment by OJayRobinson** [comment]
Thanks for bringing this to our attention, and including the excellent jsfiddles to demonstrate the problem.  

A fix has been pushed to SoundJS-NEXT

Hope that helps.
