### ISSUE TITLE
Specify absolute path to audio file

### ISSUE THREAD

**Issue by brad426** [CreateJS/SoundJS#144]
When using an absolute path that doesn't point directly to a sound file, SoundJS tries to load "/undefined" relative to the HTML page my javascript is running on.

Example:
`createjs.Sound.registerSound('http://api.voicerss.org/?key=e9a546d445234733b3113b8fb54ba6cd&src=+Hello+Brad.&hl=en-us&c=OGG');`

Internally, `_parsePath` returns `false`
Should it not just return something like `{src:"ORIGINAL_URL_HERE"}` for absolute paths that don't contain a file name?

**Comment by OJayRobinson** [comment]
currently soundjs needs a filetype to properly load audio, which is gets from filepath/filename.filetype for example "mypath/sounds.mp3".

We're considering ways to support the type of request your currently using in future releases, but currently this will not work.
Hope that helps.
