### ISSUE TITLE
"fileload" event does not fire on ie11.

### ISSUE THREAD

**Issue by gohan222** [CreateJS/SoundJS#146]
The event "fileload" does not seem to fire on ie 11.  I've also tried using preloaderjs with no success.  Just to clarify this happens with soundjs 0.6.0.  It throws an error when i try to register an audio file.  If i specify the web audio plugin the registration works but the fileload does not fire.  using soundjs 0.5.2 seems to work fine.

**Comment by OJayRobinson** [comment]
Hi, ie 11 does not support web audio, therefore the WebAudioPlugin will not successfully register as a plugin with the Sound class.

Testing ie version 11.0.9600.17498 with the latest release, the fileload event fires as expected.
You can verify using the [online demos](http://www.createjs.com/Demos/SoundJS/TestSuite).

Hope that helps.
