### ISSUE TITLE
Sounds not playing when registered again after load

### ISSUE THREAD

**Issue by fela98** [CreateJS/SoundJS#148]
According to the documentation the [createjs.Sound.registerSound()](http://createjs.com/Docs/SoundJS/classes/Sound.html#method_registerSound) method should return true if the source has already loaded internally and so it does. The problem however, is that if i call createjs.Sound.registerSound again after the sound file has been loaded, i'm unable to play the sound. It is not playing and it's playState is "playFailed".

This code fails to play:
```javascript
createjs.Sound.registerSound('test.mp3');

createjs.Sound.on('fileload', function(event) {
    createjs.Sound.registerSound('test.mp3');
    createjs.Sound.play('test.mp3');
});
```

While this works just fine:
```javascript
createjs.Sound.registerSound('test.mp3');

createjs.Sound.on('fileload', function(event) {
    //createjs.Sound.registerSound('test.mp3');
    createjs.Sound.play('test.mp3');
});
```

**Comment by OJayRobinson** [comment]
Thanks for bringing this issue to our attention, good catch.

A fix has been pushed to SoundJS-NEXT

Hope that helps.
