### ISSUE TITLE
Cordova on android music does not play.

### ISSUE THREAD

**Issue by denza** [CreateJS/SoundJS#150]
We have HTML5 game which is using soundjs for handling sounds in game.

Currently we have problem with android. Previously we have had problem with sounds in our app and we solved it using cordova media plugin. Basically it calls android native player to play sounds.

Could you please advise should we continue using SoundJS or currently it is not possible.

Thanks

**Comment by OJayRobinson** [comment]
Hi,

SoundJS has not been testing with Cordova/phonegap, but there has been some discussion in the past [here](http://community.createjs.com/discussions/soundjs/1602-soundjs-phonegap) and [here](http://community.createjs.com/discussions/soundjs/6677-mp3-file-error-in-ios-phonegap).

It seems like it is possible, but there can be issues and the causes and solutions to the issues are unclear.  I suspect it has something to do with defaulting to WebAudioPlugin which needs to load audio through xhr, which could be solved by [registering HTMLAudioPlugin](http://www.createjs.com/Docs/SoundJS/classes/Sound.html#method_registerPlugins).

Ideally we would like to create a Cordova/PhoneGap plugin, and would be happy to assist anyone who would like to try making one.

Hopefully that helps, and if you find a solution we'd like to hear about it.

**Comment by varyndev** [comment]
I finally got this to work. When loading audio files over file:, none of the documented events are being generated. this causes the load queue to hang as it starts to load as many tags as max connections are set, then none of those ever update to a completed/loaded state. Even setting the number of connections to the total number of files you want to load does not address the issue as you never get an event any of the tags has loaded causing your loader to just hang. I checked my document and the <audio> tags are added to the DOM and appear to be valid.

My solution was to add a few lines of code inside TagRequest.js load function to check the protocol is file: and if so call _handleTagComplete. This addresses the problem, keeps the load queue moving, has no impact with LoadQueue working as documented, and didn't break my app when not running under Cordova, and assumes that if loading over file: then the audio is immediately available (which it appears to be). But so far I only tested on ios I still need to test Android and Windows Phone.

**Comment by OJayRobinson** [comment]
Awesome, thanks for sharing your results.

Hopefully that will help other people with similar problems.

**Comment by lannymcnie** [comment]
We will also look at how we can solve this on our end.

**Comment by varyndev** [comment]
Another part of the solution developers need to know is you must register HTMLAudioPlugin only, and do not register the WebAudioPlugin and do not call RegisterDefaultPlugins when you are loading over file:. If WebAudioPlugin is registered all the audio tag loads fail with the file error.

**Comment by OJayRobinson** [comment]
SoundJS has added a CordovaAudioPlugin, available on [github](https://github.com/CreateJS/SoundJS), which will work with any Cordova app and tools that utilize Cordova such as PhoneGap or Ionic.  This is an optional plugin that has to be registered using createjs.Sound.registerPlugins, and requires the [Cordova Media plugin](http://plugins.cordova.io/#/package/org.apache.cordova.media).

Some issues worth noting:
* Don't forget to update your audio filepath with the appropriate prefix (for example /android_asset/www).
* Position for the Cordova Media plugin is asynchronous, so SoundInstance.position returns a best guess during playback that is synchronized when the audio is paused.  We also provide a direct mapping to the Media method with SoundInstance.getCurrentPosition.
* AudioSprite performance is not reliable, so I would advise giving them a larger margin for error.

This plugin is very new and would benefit from real world testing.  Feedback and bug reports are very welcome.  Thanks, hopefully it proves helpful.

**Comment by mayforestJ** [comment]
Just tested it with the "SoundJS: Mobile Safe" example (https://github.com/CreateJS/SoundJS/blob/master/examples/MobileSafe.html) , using PhoneGap build for iOS build. Installed and no sound. 

Code is the same as the example, except the following changes:
- comment out the "if (!createjs.Sound.initializeDefaultPlugins())" block
- add "createjs.Sound.registerPlugins([createjs.CordovaAudioPlugin]);"

You can find the test code here: https://github.com/mayforestJ/JustTest 

Questions:
1. Should I call createjs.Sound.initializeDefaultPlugins() even I need to register CordovaAudioPlugin? 
2. How to include Cordova Media plugin mentioned above while using phoneGap build?

Thanks a lot for the help!

**Comment by OJayRobinson** [comment]
Thanks for checking it out.

1. No, initializeDefaultPlugins is not needed if you call registerPlugins unless the register fails.

2.  Everything is documented in the NEXT docs, so if you unzip that locally it may be helpful.

[Cordova Media plugin](http://plugins.cordova.io/#/package/org.apache.cordova.media) is the plugin you want.  I used the following in CLI:

    cordova plugin add org.apache.cordova.media

I think you also need to wait for the Cordova device ready event before starting the soundjs code.

Hope that helps and please let us know the results.

**Comment by mayforestJ** [comment]
Thanks a lot for your kind help. 

I am new to the PhoneGap. In fact, haven't installed it yet. Just use PhoneGap Build from Adobe to try it out. I am assuming that I will need to install PhoneGap before I can include the Cordova media plugin. Or maybe I can include that plugin from PhoneGap Build? Will be back on my experiment.
