### ISSUE TITLE
Sound doesn't play when using external manifest file

### ISSUE THREAD

**Issue by Pajamaman** [CreateJS/SoundJS#153]
Sounds are not being played when I use an external manifest file. For example, this works:

    function init() {
        loader = new createjs.LoadQueue();
        loader.addEventListener('complete', handleComplete);
        loader.addEventListener('error', handleError);
        loader.installPlugin(createjs.Sound);
        loader.loadManifest({
            "path": "assets/",
            "manifest": [
                {"id": "robot", "src": "img/robot.png"},
                {"id": "beep", "src": "snd/beep.ogg"}
            ]
        });

        stage = new createjs.Stage('my-canvas');
    }

    function handleMouseDown(event) {
        createjs.Sound.play('beep');
        robot.x = event.stageX - robot.image.width/2;
        robot.y = event.stageY - robot.image.height/2;
    }

The robot is displayed on the canvas. When I click on the canvas, it moves to the new coordinates and plays a sound.

This, on the other hand, does not work:

    function init() {
        loader = new createjs.LoadQueue();
        loader.addEventListener('complete', handleComplete);
        loader.addEventListener('error', handleError);
        loader.installPlugin(createjs.Sound);
        loader.loadManifest('manifest.json');

        stage = new createjs.Stage('my-canvas');
    }

    function handleMouseDown(event) {
        createjs.Sound.play('beep');
        robot.x = event.stageX - robot.image.width/2;
        robot.y = event.stageY - robot.image.height/2;
    }

The manifest file:

    {
        "path": "assets/",
        "manifest": [
            {"id": "robot", "src": "img/robot.png"},
            {"id": "beep", "src": "snd/beep.ogg"}
        ]
    }

Using the external file, the robot is displayed on the page. When I click on the canvas, it moves to the new coordinates, but it does not play a sound. Both files are located in the root directory.

There are no console errors, but I did notice something curious. When using the external file, Chromium's Network tab logged two requests for the sound file - the first of which returned a 206 partial content response:

![screenshot from 2015-02-20 21 11 42](https://cloud.githubusercontent.com/assets/1323271/6312824/95e193c4-b945-11e4-8fd0-5e3142f617e8.png)

Whereas the inline manifest logged only one request:

![screenshot from 2015-02-20 21 12 58](https://cloud.githubusercontent.com/assets/1323271/6312825/ae57fb3c-b945-11e4-973a-33e250d9f518.png)

I'm on Chromium Version 40.0.2214.111 Ubuntu 14.04 (64-bit).

One more thing: using the external file, `loader.getItems()` only returns one object for the sprite that was loaded. With the inline manifest, it returns two - the sprite and the sound.

**Comment by Pajamaman** [comment]
I see now this may be a duplicate of CreateJS/PreloadJS#117

**Comment by OJayRobinson** [comment]
You are correct, this is a PreloadJS issue and a duplicate as you mention.  I will close this issue as it will be resolved in the linked issue.
