### ISSUE TITLE
FlashAudioPlugin ignores volume controls

### ISSUE THREAD

**Issue by christopherliu** [CreateJS/SoundJS#154]
`createjs.Sound.play(event.src, {volume:0.1})` does not change the volume when used in a FlashAudioPlugin (WebAudioPlugin works).

To help reproduce the bug, I've modified [JustPlay.html](https://github.com/christopherliu/SoundJS/blob/master/examples/JustPlay.html) in my fork. If you remove WebAudioPlugin, FlashAudioPlugin will not respect the volume settings.

(Running Python SimpleHTTPServer in the root directory is enough to get the example to work (though sometimes I have to restart the server a few times).)

**Comment by OJayRobinson** [comment]
Also, the volume reports incorrect that it has been set to 0.1 although it is actually playing at 1.

**Comment by OJayRobinson** [comment]
Thanks for reporting this issue, a fix has been pushed to the FlashAudioPlugin.swf for this, available [here](https://github.com/CreateJS/SoundJS/tree/master/src/soundjs/flashaudio).

This also fixes an identical issue with pan.

Hope that helps.

**Comment by christopherliu** [comment]
Yes, that's working now. Thanks!
