### ISSUE TITLE
Sounds doesnt work on ipad mini.

### ISSUE THREAD

**Issue by Kfhonics** [CreateJS/SoundJS#156]
For some reasons sounds do not play when tested on an ipad mini. Not my coding, not even your site. The incremental loader works but no sound on my end. As per your site testing area (http://createjs.com/Demos/SoundJS/TestSuite), on the ipad mini the sound selections do not even show - See attached. 

Let me know.
![11003950_10155204352855591_145504301_n](https://cloud.githubusercontent.com/assets/10951621/6402843/3347ceb8-bde1-11e4-9e06-f03d1dd21433.jpg)

**Comment by OJayRobinson** [comment]
Testing on an ipad mini ios v 8.1.3 sound works with the soundGrid demo, but not the testSuite which is a little odd.  I suspect this is related to playback needing to happening in a user event (touch) to unmute on iOS.  The [Mobile Safe Tutorial](http://www.createjs.com/tutorials/Mobile%20Safe%20Approach/) might be useful if you want to learn more.

In TestSuite, the sounds are there but you need to click the list to select one.  In the image it is showing you that you have selected 0 sounds.

Hope that helps.
