### ISSUE TITLE
WindowsPhone error

### ISSUE THREAD

**Issue by krzysztof-o** [CreateJS/SoundJS#157]
Hi,
I get indeterministic errors on Windows Error:

```
ERROR Unexpected call to method or property access.,http://10.2.1.251:8000/core/lib/createjs-soundjs-0.6.0.combined.js,7094,3
```

This is about this line: ```this._playbackResource.play();``` inside method: ```p._handleSoundReady = function (event) {```

Does anyone have a clue what the problem can be?

**Comment by OJayRobinson** [comment]
Testing on a Nokia Lumia 520 Windows Phone 8.1, I am getting audio playback but very poor performance with the latest [SoundJS-NEXT](https://github.com/CreateJS/SoundJS).

The error tells me that you are using HTMLAudioPlugin and that this._playbackResource in HTMLAudioSoundInstance has not been set properly.  _playbackResource in this case should be an audio tag, so something has gone wrong.  The only scenario I can think of is if you created a SoundInstance and then removed the related src, and even then I think it would still quietly error out.

Can you try testing using the latest SoundJS-NEXT and the examples in the repo and see if you can reproduce the error?

Hope that helps.

**Comment by krzysztof-o** [comment]
Sorry for the delay. The error occured on 0.60 version. On NEXT version it works fine.
