### ISSUE TITLE
Nexus 7, Chrome 40.0.2214.109; no _handleError method, causes TypeError

### ISSUE THREAD

**Issue by clickblipclick** [CreateJS/SoundJS#159]
Hi,

When registering new sounds, `_sendComplete` throws the following error:

`Uncaught TypeError: Cannot read property 'apply' of undefined`

due to `this.handleError` being undefined.

I cannot reproduce on any other browser, and it seems to be happening whether I use 0.6.0 or NEXT combined.

Thanks for your hard work on this plugin!

**Comment by OJayRobinson** [comment]
Hi, running the latest [SoundJS-NEXT](https://github.com/CreateJS/SoundJS), the [Sound Grid example](http://www.createjs.com/Demos/SoundJS/SoundGrid) works without issue on the same version of Chrome on Samsung Galaxy S3 phone.  SoundJS has actually worked in Chrome on Android for some time now and has been successfully tested on a Nexus in the past.

I suspect there is something else going on in the code you are running.  You can verify by running Sound Grid on the Nexus 7.

Hope that helps.

**Comment by clickblipclick** [comment]
Hm, thank you. Very strange, that example does work for me. I have a minimal example here using the same soundjs version from the example:

http://s3.ralphandco.com/audiotest/

If I'm making a stupid mistake I apologize, but I've been trying a few different things and that error persists.

Thanks!

**Comment by OJayRobinson** [comment]
Thanks for the minimal example, the code looks mostly fine.  
maybe try replacing:
`createjs.Sound.on('fileload', createjs.proxy(loadHandler, this));`

with this, as in this context this is just window:
`createjs.Sound.on('fileload', loadHandler));`

It also might have something to do with mobile devices sometimes requiring loading and playback to happen in user events (touch).  The [Mobile Safe Tutorial](http://www.createjs.com/tutorials/Mobile%20Safe%20Approach/) has more information that you might find helpful.  This hasn't been the case in chrome on android for awhile as far as I know, but perhaps the Nexus 7 has restrictions I am unaware of.

Hope that helps.
