### ISSUE TITLE
some mp3 files fail loading in ios deviced

### ISSUE THREAD

**Issue by assafsahar** [CreateJS/SoundJS#160]
hi there,
I'm struggling with this for a while and appreciate any help.
I'm using preloadJS to load both PNGs and audio files (ogg/mp3).
Everything work nicely except for ios devices where strangely, some of the files (mp3) causes loading to stop with a sounJS "TypeError" - 'undefined' is not an object (version 0.6.0.combined.js line 237).

![ioserror](https://cloud.githubusercontent.com/assets/2690737/6833479/1a3c2224-d336-11e4-910c-a4cbefc63744.png)

When I exclude these files from the manifest I get everything working just fine. The thing is that there are other mp3 files which doesn't cause any issues.
Also, if I replace the problematic files with other mp3 files (which I know are working good) it works with no errors, so I know the issue has nothing to do with the amount of files to load

.
In android devices and windows PCs everyting works, even when I force using those MP3 files.

any suggestions?

**Comment by OJayRobinson** [comment]
Hi, that is not something I have seen before.  It sounds like the problem is with audio encoding.  We've found that default settings work best.

You may also want to try the latest NEXT release of [SoundJS](https://github.com/CreateJS/SoundJS/tree/master/lib) and [PreloadJS](https://github.com/CreateJS/PreloadJS/tree/master/lib) as both contain fixes.

If neither of those help you, if you could try creating a minimal code example of the issue and I could take a look.

Hope that helps.

**Comment by assafsahar** [comment]
Thanks for the quick reply!
I've replaced the files to the latest NEXT releases.
Now I get everything loading with no errors, but I can see that those specific files are skipped (catching the error event).
I made an example to show you.
You can see it here:
http://codactive.com/work/gingim/turtles/test/index_example.html
It should only present the progress of loading and at the end show a blank white screen with a gray frame. If you test it with ios device you'll see the loading stops at 100%. I'm using mobileConsole to show the console's log in the device.

This is the code at the main JS file:

```
$(document).ready(function() {

    init();
});

var stage;
var canvas;
var ticker;
var frameRate;
var manifest;
var totalLoaded;
var queue;
var percentageText;
var preloaderContainer;

function init(){

    mobileConsole.show();

    // auto scale canvas
    canvas = $('canvas');
    new AutoScaler('canvas', canvas.width(), canvas.height());

    // set stage
    stage = new Stage('canvas');
    stage.enableMouseOver();
    stage.width = canvas.width();
    stage.height = canvas.height();


    // onEnterFrame..
    Ticker.fps = 24;
    Ticker.addEventListener("tick", stage);

    Touch.enable(stage);

    // preloader
    preloaderContainer = new Container();
    percentageText = new createjs.Text("50%", "30px Arial", "#ff7700");
    percentageText.x = stage.width/2;
    percentageText.y = stage.height/2 + 50;
    preloaderContainer.addChild(percentageText);
    stage.addChild(preloaderContainer);

    // set variables values
    totalLoaded = 0; // for calculating number of loaded files
    frameRate = 24; // general animation frame rate

    loadAssets();
}

function loadAssets(){
    if(isDevice()){
        manifest = [
            {src:"images/mobile/bg.png", id:"bg"},
            {src:"sounds/countingTurtle/num1.ogg", id:"countingTurtle1"},
            {src:"sounds/countingTurtle/num2.ogg", id:"countingTurtle2"},
            {src:"sounds/countingTurtle/num3.ogg", id:"countingTurtle3"},
            {src:"sounds/musicalTurtle/music1.ogg", id:"musicalTurtle1"},
            {src:"sounds/musicalTurtle/music2.ogg", id:"musicalTurtle2"},
            {src:"sounds/musicalTurtle/music3.ogg", id:"musicalTurtle3"},
        ];
    }
    else{
        manifest = [
            {src:"images/bg.png", id:"bg"},
            {src:"sounds/countingTurtle/num1.ogg", id:"countingTurtle1"},
            {src:"sounds/countingTurtle/num2.ogg", id:"countingTurtle2"},
            {src:"sounds/countingTurtle/num3.ogg", id:"countingTurtle3"},
            {src:"sounds/musicalTurtle/music1.mp3", id:"musicalTurtle1"},
            {src:"sounds/musicalTurtle/music2.ogg", id:"musicalTurtle2"},
            {src:"sounds/musicalTurtle/music3.ogg", id:"musicalTurtle3"}
        ];
    }

    // Adds FlashAudioPlugin as a fallback if WebAudio and HTMLAudio do not work.
    FlashAudioPlugin.swfPath = "./vendor/soundjs";
    Sound.registerPlugins([WebAudioPlugin, HTMLAudioPlugin, FlashAudioPlugin]);

    // handle assets' loading events
    queue = new LoadQueue(false);
    Sound.alternateExtensions = ["mp3"];
    queue.installPlugin(Sound);
    queue.addEventListener("fileload", handleFileLoad);
    queue.addEventListener("complete", handleComplete);
    queue.addEventListener("progress", handleProgress);
    queue.addEventListener("error", handleFileError);

    queue.loadManifest(manifest,true,"./src/assets/");
}

// render stage
function updateStage() {
    stage.update();
}

function handleFileError(event)
{
    //use event.loaded to get the percentage of the loading
    console.log("handleFileError, event.message="+event.message);
}

function handleProgress(event)
{
    //use event.loaded to get the percentage of the loading
    console.log("event.loaded="+event.loaded);

    if(percentageText){
        percentageText.text=Math.round(event.loaded * 100) + "%";
    }

}

function handleComplete(event) {
    //triggered when all loading is complete
    console.log("handleComplete ", "totalLoaded="+totalLoaded,"manifest.length="+manifest.length);
    // if all loaded, start building the page

}

function handleFileLoad(event) {
    //triggered when an individual file completes loading
    console.log("A file has loaded of type: " + event.item.type,"event.item.src=" + event.item.src);
      switch(event.item.type)
   {

        case "image":
            //image loaded
            var img = new Image();
            img.src = event.item.src;
            img.onload = handleLoadComplete;
            window[event.item.id] = new Bitmap(img);
            break;

        case "sound":
            //sound loaded
            handleLoadComplete();
            break;
    }
}

function handleLoadComplete(event)
{
    console.log("handleLoadComplete");

    totalLoaded++;

    if(manifest.length==totalLoaded)
    {
        stage.removeChild(preloaderContainer);
        addMainView();
    }
}

// build page
function addMainView(){
    console.log("addMainView");

    // first layer is the background
    stage.addChild(bg);

    // render screen
    updateStage();
}

```

**Comment by assafsahar** [comment]
note that music1.mp3 & music3.mp3 are the problematic files.
also, I've created separated manifests for mobile devices and pcs just for testing purposes.

Thanks!

**Comment by OJayRobinson** [comment]
Hi, if there are specific files that are causing issues than it is almost certainly an audio encoding issue.

I would suggest looking at the encoding from a working file and duplicating it on the ones giving you problems.

Hope that helps.

**Comment by assafsahar** [comment]
I think that my client purchased those files through the internet as MP3.
is there a way to look at the encoding? how can i duplicate the encoding
from other files?
thanks again for your help!
בתאריך 26 במרץ 2015 17:54, ‏"OJay" <notifications@github.com> כתב:

**Comment by wdamien** [comment]
@assafsahar The easiest solution is to use http://audacity.sourceforge.net/ or if your feeling adventurous try http://lame.sourceforge.net/ (Which audacity uses in the background). First try exporting the MP3 files from audacity, if that fails, play around with the encoding options. For more details on supported media formats checkout https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by assafsahar** [comment]
Thanks a lot, I've played with the encoding using a free software called
Freemake Audio Converter and this indeed solved the problem!!


 *אסף סהר       |     *
 קודאקטיב - תכנות ופיתוח אפליקציות ומשחקים.

 דוא"ל: assaf@codactive.com
טלפון: 054-4850-233
לאתר ותיק עבודות <http://codactive.com>
לדירוג לקוחות <http://www.facebook.com/codactive/app_352438281441731>

      <http://www.facebook.com/assafsahar123>
<http://www.linkedin.com/in/assafsahar>
   Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
