### ISSUE TITLE
removeAllSounds breaks cachebusting

### ISSUE THREAD

**Issue by Rycochet** [CreateJS/SoundJS#163]
I've got an app that can dynamically add plugins which can add sounds - as the app hasn't got any control or knowledge of what's being loaded it clears out all createJS stuff between plugin loads - but when the plugin tries to load the same sound again (running the same line of code) it breaks the cache busting by appending a second (and third etc) ```?_=1234567890``` timestamp on the end.

In other words each request grows -

```
filename.mp3?_=1234567890
filename.mp3?_=1234567890?_=1234567891
filename.mp3?_=1234567890?_=1234567891?_=1234567892
filename.mp3?_=1234567890?_=1234567891?_=1234567892?_=1234567893
filename.mp3?_=1234567890?_=1234567891?_=1234567892?_=1234567893?_=1234567894
etc
```

I'm not sure if this is SoundJS directly, but as it's only affecting this I'm reporting here - it could easily be PreloadJS, but I don't know the internals.

While it's technically valid, it does break things by using a ? instead of a & sub-delim (or only adding it once when requesting and not before caching the file name).

**Comment by OJayRobinson** [comment]
Hmm, that's a bit of a stumper.  Since 0.6.0 PreloadJS and SoundJS share some base loading code, I would expect any problem would effect them both.  SoundJS does not add anything like this to file requests, and as far as I know neither does PreloadJS.  If you could track down where that is getting added or create a minimal code example that shows the problem I'd be happy to dig into it deeper.

**Comment by Rycochet** [comment]
I did originally think it might be jQuery related due to the pattern - but globally turning that off made no difference.

Sadly the code handling everything is really large (20k+lines total) and (mostly) required for everything, but the registering lines are basically:

```
var manifest = [
		{src: "sounds/filename.mp3", id: "set_but_ignored"}
	]
createjs.Sound.registerSounds(manifest);
```

And the clearing things is:

```
if (window.createjs) {
	window.createjs.Ticker.removeAllEventListeners();
	window.createjs.Sound.removeAllSounds();
}
```

The source of the sounds is the output of the flash->javascript converter, wrapped for requirejs, then paths for the manifest are dynamically adjusted.

**Comment by OJayRobinson** [comment]
Interesting.

The first thing I would suggest is to the get the latest SoundJS-Next and PreloadJS-Next files from github.  SoundJS has deprecated some methods, so if any console errors come up with the switch that is the likely cause.  The deprecated methods are all in the [current docs](http://www.createjs.com/Docs/SoundJS/modules/SoundJS.html) along with links to replacements.  This will get you the latest bug fixes and refinements.

If there are still problems after the libs change, breakpoint the registerSounds method and step through until you see the src change.  As far as I know the output from flash does not inject anything, so it will be interesting to see where this leads.

Hope that helps.
