### ISSUE TITLE
InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode' Chrome 43

### ISSUE THREAD

**Issue by raldred** [CreateJS/SoundJS#168]
Looks like Google changed something,
During cleanup when a sound completes an error is thrown in Chrome 43 (tested on OSX) Firefox fine.

`Failed to execute 'disconnect' on 'AudioNode'`

This error is unexpected and should probably be caught within #cleanUpAudioNode.
It currently causes in the app/game execution to halt.

![screen shot 2015-06-03 at 15 35 29](https://cloud.githubusercontent.com/assets/37096/7962649/62d29d36-0a06-11e5-8fdb-05a2f367704e.png)

**Comment by raldred** [comment]
Sorry this was fixed a while ago in c796dae70
TBH the game is using a version from last year.

**Comment by OJayRobinson** [comment]
You might want to try 0.6.1 that just got released, but probably review the breaking changes in the [VERSIONS](https://github.com/CreateJS/SoundJS/blob/master/VERSIONS.txt) file as there are more than a couple.
