### ISSUE TITLE
Have you noticed a limit to mp3 length on Android

### ISSUE THREAD

**Issue by macguffin** [CreateJS/SoundJS#172]
Hi wondered if you had noticed a cut off of about 60 seconds when playing an mp3 in Chrome on Android. I have an audio sprite and all the sounds work fine on iPhone but in android the last few never get played.
If I just play the entire audio clip it always seems to cut off at about 60 seconds. I expect this is an Android/Chrome issue but just wanted to check  there wasn't a limit set.

Thanks

**Comment by OJayRobinson** [comment]
Chrome on android can play audio of any reasonable length.  See this [example](http://www.createjs.com/demos/soundjs/webaudionodeinsertion) for an audio clip that is longer than 60 seconds and works on android Chrome v43.0.2357.92

So something else is happening to make the clip not work past 60 seconds.  My best guess without further information is that it is related to audio encoding.

As a side note, if you force HTMLAudioPlugin, audio sprites have a known issue in chrome that they will only load enough to play through at the current download speed so switching to another sprite (aka another position in the audio tag) could cause a delay.

Hope that helps.

**Comment by macguffin** [comment]
Yes you were right it was the encoding. I bumped it up to 44100HZ and the entire clip now plays. I was trying to make the audio as small as possible, I'll just have to watch out for this when using audiosprites. Thanks for the reply.
