### ISSUE TITLE
iOS homescreen app when minimised crashes on reopen

### ISSUE THREAD

**Issue by BrendonCon** [CreateJS/SoundJS#174]
Hey guys, I have created a simple sandbox which includes SoundJS, noticed an issue with home screen (seems to happen on most sound engines) where if you add your page to home screen, launch the app, touch to load in the sound, then minimise the app and re-open it, you will see the app actually crash. I think this is related to how apple handles home screen apps in general. Your thoughts?

**Comment by wdamien** [comment]
Yes, we have seen this before with IOS running audio from the home screen. Unfortunately we have not found any work arounds or fixes, but have tracked it down to a bug in the ios home screen implementation. For more details checkout #46

**Comment by BrendonCon** [comment]
Thanks so much for the response, we have been dealing with this issue on home screen for some time now, such a pity that sound behaves this way. At least I know now not to waste anymore time on it. Cheers and compliments on a great API btw.
