### ISSUE TITLE
How to pause sound ?

### ISSUE THREAD

**Issue by MichaelGong** [CreateJS/SoundJS#178]
I want to pause the sound that is playing in loop,How can I do that?

**Comment by lannymcnie** [comment]
Store a reference to the sound instance, and then use the `pause` method.

```javascript
var instance = createjs.Sound.play("soundId", {loop:-1});
instance.pause();
```

**Comment by MichaelGong** [comment]
I pause a sound ,then play another sound. Sometimes the both sound will be played,why? How to resolve the problem?

**Comment by lannymcnie** [comment]
That sounds like a code issue. Feel free to post your code or a sample, and someone can check it out. This should definitely not happen.

**Comment by Serching** [comment]
i m used Adobe animate,with hml5 Canvas, but i can´t paused audio in  Button. Help me please. Sorry for my english

**Comment by lannymcnie** [comment]
@Serching Feel free to post some code, or open a thread on StackOverflow. This forum is mainly for reporting issues with the library. Cheers.

**Comment by Serching** [comment]
this.anda.addEventListener("click", fl_ClickToGoToAndStopAtFrame.bind(this));

function fl_ClickToGoToAndStopAtFrame() {
	//sym.$("audio1")[0].pause();

	this.stop();
	//createjs.Sound.stop("audio1");
	//instance.pause("audio1");

function play() {
  audio.play();
}

function pause() {
  if (audio.paused) {
    audio.play();
  } else {
    audio.pause();
  }
}
}

**Comment by lannymcnie** [comment]
1. The static `Sound.stop()` is only used to stop all sounds. You can't pass a string reference to it like `play()`. http://createjs.com/docs/soundjs/classes/Sound.html#method_stop
2. You need a reference to your sound to call methods on it. The `instance.pause()` is closer to the correct approach, however there is no `pause()` method (depending on your version, I believe it used to function this way). Use the `paused` property instead. http://createjs.com/docs/soundjs/classes/AbstractSoundInstance.html#property_paused
3. What is `audio`? You don't show it playing here. You will have to make sure you have a correct reference to the sound to pause/resume it.

Check out the examples in GitHub.

**Comment by Serching** [comment]
ok... very much thanks lannymcnie, i m reading the help and the examples...

**Comment by didifend** [comment]
`// SoundJs versi 1.0.0 (Next)

var bgMusic;
function playBgMusik1(){
	bgMusic = ini.playSound("bgsound", true, playBgMusik1); // 
}

function stopSound(){
bgMusic.stop(); // stop the specf. sound
}

this.playSound = function (idSound, loopSound,, fxSound) {
	var instance = createjs.Sound.play(idSound);
	instance.on("complete", handleComplete, this);
	instance.volume = 0.5;
	function handleComplete() {
		if(fxSound && loopSound)
			fxSound();
	}
	return instance;
}`
