### ISSUE TITLE
I pause a sound ,then play another sound. Sometimes the both sound will be played.

### ISSUE THREAD

**Issue by MichaelGong** [CreateJS/SoundJS#179]
I pause a sound ,then play another sound. Sometimes the both sound will be played,why? How to resolve the problem?

**Comment by lannymcnie** [comment]
Can you post code? It is hard to tell what is going on with your description.

**Comment by lannymcnie** [comment]
Closing this issue. If you can still reproduce this, and can post a test case, feel free to re-open.
