### ISSUE TITLE
Sound balance issue with latest version of Chrome

### ISSUE THREAD

**Issue by glecollinet** [CreateJS/SoundJS#182]
Since updating to Google Chrome 44.0.2403.89, all sounds only play in the right channel.
This happens on the homepage demo: http://www.createjs.com/soundjs

**Comment by sccottt** [comment]
Also noticed this issue today. :[

**Comment by cvissie** [comment]
It seems they managed to break/change the PannerNode. 

It only works now if you set the pan position to -0.5.

**Comment by cvissie** [comment]
After playing around - I also see that "equalpower" panningModel is affected. Using "HRTF" works. I just don't know what is the support for HRTF.

**Comment by krzysztof-o** [comment]
I am also experiencing this problem. Does anyone have a quick workaround?

**Comment by andrewstart** [comment]
New versions of Chrome and Firefox have StereoPannerNode, which is probably preferable to PannerNode anyway, but perhaps using that works properly?

**Comment by bitflower** [comment]
@cvissie's workaround worked for me: I used 0.5 without the minus though because it -0.5 it felt like it's slightly shifted to the left. Thank god I play all sounds through a wrapper function :-)

**Comment by gskinner** [comment]
We're still looking into a long term fix for this, but it seems to relate specifically to a pan value of `0`. To work around the issue in the interim, you can set pan to a nearly zero value, like:

`mySound.pan = 0.0001`

**Comment by macguffin** [comment]
If you are loading audio with preloadJS and soundJS 0.6.1 you can do the following to fix all sounds as they load. 
This uses `setDefaultPlayProps` to apply Grant's pan fix to all audio.

Add a listener to your load queue for file load: 
`LoadQ.addEventListener("fileload",fileload);`
    
    fileLoad(e) {

    var item = e.item,
        type = item.type;

    switch (type) {
    case createjs.AbstractLoader.SOUND:

    var item = e.item,
        src = item.src;
  
    createjs.Sound.setDefaultPlayProps(src, {pan: 0.0001});
    break;
    }
    }

**Comment by wdamien** [comment]
A new NEXT version has been pushed, with a fix for this included.

**Comment by cyrrill** [comment]
I am having this issue with Chrome v 45.0.2454.85 (64-bit) on Fedora, using the latest NEXT version (a648299)

**Comment by azack** [comment]
Noting that #185 addresses this
