### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by mnquintana** [CreateJS/SoundJS#191]
It would be really awesome to see this library support CommonJS and get added to `npm`, so it could be `require`d in contexts like [Browserify](http://browserify.org/) or [Electron](http://electron.atom.io/).

**Comment by wdamien** [comment]
Related to; https://github.com/CreateJS/PreloadJS/issues/85

**Comment by gugiserman** [comment]
yes!

**Comment by cbrandolino** [comment]
+1 that would be so great!

**Comment by wittnl** [comment]
+1

**Comment by slurmulon** [comment]
+1

**Comment by danny-andrews** [comment]
+1

**Comment by j-verre** [comment]
+1

**Comment by fela98** [comment]
+1

**Comment by lannymcnie** [comment]
Cleaned out a bunch of +1 comments. We definitely hear you, and want to support this soon. Likely it will be in conjunction with our in-progress ES6 version.

Cheers!

**Comment by lannymcnie** [comment]
We have pushed npm support for the latest tagged version.

**Comment by Zalvex** [comment]
I'm loading the module with ES6 'import' and it cannot find module 'soundjs'. Main in package.json is referencing 'soundjs' instead of 'lib/soundjs'.

**Comment by lannymcnie** [comment]
Yep, we have to update our package. Unfortunately there is no module support at this time, so that fix won't let you use the library as a package yet.

**Comment by matthewoates** [comment]
This is fundamental for any modern web app within the last few years. Is this supported? I see no mention of it on the site or this repo.
