### ISSUE TITLE
Any plan for `stop` event of `AbstractSoundInstance`?

### ISSUE THREAD

**Issue by toruta39** [CreateJS/SoundJS#194]
Since AbstractSoundInstance emits no event when `Sound.stop()` is called, there's no way to know if a sound instance is stopped.

Is there any future plan to implement a `stop` event for `AbstractSoundInstance`? Or is there some better way to fulfill this kind of task?

For now, I just monkey patch `AbstractSoundInstance.prototype.stop` method to enforce it emit a `stop` event, in order to let me know when a sound instance is stopped.

```JavaScript
var _stop = createjs.AbstractSoundInstance.prototype.stop;
createjs.AbstractSoundInstance.prototype.stop = function() {
  _stop.apply(this, arguments);
  this._sendEvent('stop');
}
```

**Comment by lannymcnie** [comment]
Any particular reason why you need a stop event? Since stop doesn't happen automatically, it is initiated by code. Open to adding it, just wondering what your use case is.

**Comment by toruta39** [comment]
In my working project, there're multiple "sound button"s that play different sounds and also holds the sound state (loading/idle/playing/paused), and one "stop all button" which will simply calling `Sound.stop()`.

So for those sound buttons, I think it maybe more intuitive to add listener to the sound instance for any state updates (like working with media element).
