### ISSUE TITLE
Too slow decoding of OGG @ Chrome

### ISSUE THREAD

**Issue by purportex** [CreateJS/SoundJS#198]
In case of using one audio sprite with multiple sound samples and loading the whole single audio track at once there is a big delay between load completes and decoding completes. Moreover, there is no way to track a progress. It means more than 1/2 minute of decoding on Android devices.

Is it possible to use Audiocogs to decode MP3 or OGG by JS and then pass decoded data to SoundJS?

**Comment by konistehrad** [comment]
This is a known, open bug on Android Chrome: https://code.google.com/p/chromium/issues/detail?id=424174
