### ISSUE TITLE
Invalid Method request GET.html

### ISSUE THREAD

**Issue by ikristher** [CreateJS/SoundJS#204]
The library is working without a server but running with apache, I get this error
[Tue Sep 15 16:51:58.255447 2015] [core:error] [pid 7260:tid 1712] [client ::1:52409] AH00135: Invalid method in request GET.html /memorygame/sounds/right.mp3 HTTP/1.1, referer: http://localhost/memorygame/

in the minified version of createjs, it worked after replacing GET.html to GET.

**Comment by wdamien** [comment]
This looks like an issue with your implementation, not a SoundJS bug. I'm closing this issue for now, but if you have sample code that demonstrates a SoundJS bug feel free to re-open it.
