### ISSUE TITLE
IE9 XHRRequest addEventListener, including latest PreloadJS 

### ISSUE THREAD

**Issue by bigtimebuddy** [CreateJS/SoundJS#221]
PreloadJS has some fixes for IE9 that haven't been integrated into SoundJS.  For instance, the load function (links below) in XHRRequest in SoundJS doesn't check for `addEventListener` (not in IE9). Is there a reason why these common code classes haven't been updated from PreloadJS?

* [PreloadJS's load function](https://github.com/createjs/preloadjs/blob/master/src/preloadjs/net/XHRRequest.js#L173-L218)
* [SoundJS's older load function](https://github.com/createjs/SoundJS/blob/master/src/preloadjs/net/XHRRequest.js#L173-L205)

**Comment by lannymcnie** [comment]
No reason. Good suggestion.

**Comment by lannymcnie** [comment]
Thank you for pointing this out, it should be resolved shortly.

**Comment by bigtimebuddy** [comment]
Thanks @lannymcnie! I appreciate the quick response.

**Comment by lannymcnie** [comment]
An update has been pushed to GitHub. Cheers!
