### ISSUE TITLE
CDN jsDelivr outdated

### ISSUE THREAD

**Issue by delmicio** [CreateJS/SoundJS#227]
http://www.jsdelivr.com/projects/soundjs

It's on 0.4.1 and should be on 0.6.*

**Comment by jimaek** [comment]
Its possible to enable auto-updates if there is a good source for the official files.
For example this repo cant be used because the filenames here https://github.com/CreateJS/SoundJS/tree/0.6.2/lib contain the version inside them

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by lannymcnie** [comment]
We have simplified naming, and jsdelivr should be updated shortly.
