### ISSUE TITLE
Safari undefined is not an object (evaluating 'a.apply')

### ISSUE THREAD

**Issue by smks** [CreateJS/SoundJS#228]
```
this.createjs = this.createjs || {}, function() {
    "use strict";
    createjs.proxy = function(a, b) {
        var c = Array.prototype.slice.call(arguments, 2);
        return function() {
            return a.apply(b, Array.prototype.slice.call(arguments, 0).concat(c))
        }
    }
```

This is when loading sound.min.js from openfl / lime in 'safari' only. Other browsers are fine.

**Comment by idir** [comment]
Same issue for me

**Comment by lannymcnie** [comment]
Looks like a null event handler. Not sure why this would be only in Safari. Closing for now, as we won't be fixing this specifically, and the next version will be ES6, so the proxy is officially dead!
