### ISSUE TITLE
Use registerSound function to register an audio by using a base64 or binary string rather than a path

### ISSUE THREAD

**Issue by gmiano** [CreateJS/SoundJS#239]
Hello, 
I am trying to register within Soundjs API a new sound which is stored in a variable as a base64 string. Is it possible?

Thanks for reply.

**Comment by gmiano** [comment]
Nobody can help me?

My scenario is something like this:
- I download audio tracks by using external APIs
- I receive as response tracks as base64 string
- I would register them in sound js (there is no way to use a url reference because they are built on fly)

I would like to register these tracks in soundjs to use them within an Animate CC project. Is it possible to use data to register an audio rather than an URL.

**Comment by lannymcnie** [comment]
Closing this in favour of the duplicate #200
