### ISSUE TITLE
Sound stops when opening inspector in Firefox

### ISSUE THREAD

**Issue by itsmequinn** [CreateJS/SoundJS#241]
We've found that when a sound is playing in Firefox and you open the inspector (either with a keyboard shortcut, through the hamburger drawer menu in the top right or right clicking to inspect an element), the sound stops playing and any subsequent sound will not play. If you close the inspector and open it again, sounds play again. For instance, on the SoundJS home page, if you click the middle sound in the second from the top row in the demo grid and then inspect, the sound will stop. I mention that sound in particular because it has a longer duration, which allows you to start it and inspect before it ends.

I've tested this using a normal embedded html audio element and the issue does not seem to happen, which is why I've posted this here. I'm not sure if this is a browser bug or a bug in the framework, but I couldn't find any mention of it either here or on Mozilla's Firefox bug tracker.

**Comment by michaelwoods** [comment]
It does appear to be a browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1259831

**Comment by lannymcnie** [comment]
Thanks @michaelwoods 
Closing this bug.
