### ISSUE TITLE
Can you play multiple sounds on a single button click?

### ISSUE THREAD

**Issue by AshleyJBartlett** [CreateJS/SoundJS#246]
Basically, I will have multiple sound clips which have different different musical  instruments playing. I would like them to then be able to be played together in sync on the click of a button so they play as part of an orchestra. The clips will only be short, maybe around 30 seconds.

**Comment by lannymcnie** [comment]
You can play whatever sounds you want, as long as you are not on a mobile device that limits to one sound at a time (pretty much any device without WebAudio support)
