### ISSUE TITLE
Replace .txt files with .md files

### ISSUE THREAD

**Issue by zdroid** [CreateJS/SoundJS#249]
I think there's no reason to use `.txt` files on GitHub, because it supports Markdown which is way easier to read. `VERSIONS.txt` and `README_CREATEJS_NAMESPACE.txt` are redundantly hard to read and the latter has bad name. `LICENSE.txt` is still okay, but other files aren't.

Just a suggestion. I think everybody would profit from changing those files type and syntax to Markdown.

**Comment by lannymcnie** [comment]
Good suggestion. I think we can probably retire the NAMESPACE file anyways -- it was important when we added the namespace, since it broke everything -- but its been like 4 years. Looks like it has already been removed on the EaselJS repository, so we will make these changes shortly.

**Comment by zdroid** [comment]
Great to hear. :clap:
