### ISSUE TITLE
Mobile Chrome sound play lag.

### ISSUE THREAD

**Issue by devMikeG** [CreateJS/SoundJS#252]
It seems that there is a slight lag every time I try to play a sound on mobile chrome.
The audio file has no silence at the start. I am preloading the sound.
This only happens on Chrome, it also happens when I completely bypass SoundJS (and use HTML Audio), so I'm confident that SoundJS isn't actually the culprit here, but I'm wondering if you guys have seent this issue before and could possibly suggest a workaround?

Any help appreciated.
My code is below:

Kind regards

Mike

```js
playOneShotAudio("LeadNote1", 1);

function playOneShotAudio(sSoundID, fVolume) {
    var oPlayProperties = {
            interrupt: createjs.Sound.INTERRUPT_NONE,
            delay: 0,
            offset: 0,
            loop: 0, // single shot sound
            volume: fVolume
        },
        oSound = createjs.Sound.play(sSoundID, oPlayProperties);
    return oSound;
}
```

**Comment by devMikeG** [comment]
Hi Lanny, actually no, I used a few diifferent handlers to test that a while back, makes no difference. In researching this further it's actually Android's terrible audio engine and the latency it produces. It's a known problem that has been 'getting better' with each new release of Android.

**Comment by lannymcnie** [comment]
Closing, unless there is something else we can do with this. Feel free to reopen with more information.
