### ISSUE TITLE
SoundJS Examples fail

### ISSUE THREAD

**Issue by supermensa** [CreateJS/SoundJS#258]
When trying to run examples from my own server, I get these errors:

```
soundjs-NEXT.combined.js:1513  
Uncaught TypeError: Cannot read property 'POST' of undefined(…)
(anonymous function) @ soundjs-NEXT.combined.js:1513
(anonymous function) @ soundjs-NEXT.combined.js:2078

07_WebAudioNodeInsertion.html:74
Uncaught TypeError: Cannot read property 'registerPlugins' of undefined(…)
init @ 07_WebAudioNodeInsertion.html:74
onload @ 07_WebAudioNodeInsertion.html:12
```

Could possibly be linked with this commit? [Updated shared classes to the latest](https://github.com/CreateJS/SoundJS/commit/732bf965096233d5d65487766f409c4dc1b44e8c)

Edit: The 'PlayOnce' branch works fine.

**Comment by lannymcnie** [comment]
Yes, it looks like we need to update our internal utility that copies shared classes between repositories. Sorry for the inconvenience -- I will push a fix shortly.

**Comment by lannymcnie** [comment]
Thanks for the report. This has been rectified, and the latest has been pushed up. I did some quick tests with all the included demos, and it looks good now.

The latest commits also include a few other fixes, so please feel free to report any remaining issues.
