### ISSUE TITLE
Sound.muted and Sound.volume doesn't work

### ISSUE THREAD

**Issue by PythonFanboy** [CreateJS/SoundJS#268]
The below example plays sound, although it shouldn't:
```
createjs.Sound.muted = true;
createjs.Sound.volume = 0;
createjs.Sound.play('myId');
```
Using v0.6.2, MP3 and Chrome.

**Comment by lannymcnie** [comment]
Looks like this only affects HTML Audio. I have made a fix, and will push it shortly.

**Comment by lannymcnie** [comment]
Fixed, and pushed!

**Comment by Gaikov** [comment]
I have the same problem.
Can you show a commit? I want to merge in my version of soundjs
