### ISSUE TITLE
the Sound.play does not work  when the fileload event.

### ISSUE THREAD

**Issue by AsJoy** [CreateJS/SoundJS#271]
the Sound.play does not work  when the fileload event. does it because the audio has not been decoded from ArrayBuffer? if so,  is there any event after The audio decoded
my code is given below: 
```
  loader.addEventListener('fileload', e => {
    Sound.paly('bgm')
    res(e)
  })
```
== I'm sorry about My English

**Comment by lannymcnie** [comment]
Can you provide a sample? The fileload definitely fires _after_ the buffer is decoded. I am marking as "can not reproduce" unless you can provide reproduction steps.
