### ISSUE TITLE
SoundJS's AbstractPlugin.js had a set method problem, At version 1.0.0

### ISSUE THREAD

**Issue by MIKUScallion** [CreateJS/SoundJS#281]
https://github.com/CreateJS/SoundJS/blob/master/src/soundjs/AbstractPlugin.js

```js
	/**
	 * Handles internal preload completion.
	 * @method _handlePreloadComplete
	 * @param event
	 * @protected
	 */
	p._handlePreloadComplete = function (event) {
		var src = event.target.getItem().src;
		this._audioSources[src] = event.result;
		for (var i = 0, l = this._soundInstances[src].length; i < l; i++) {
			var item = this._soundInstances[src][i];
			item.setPlaybackResource(this._audioSources[src]);
			// ToDo consider adding play call here if playstate == playfailed
			this._soundInstances[src] = null;
		}
	};
```

This method call a set method named **setPlaybackResource**, then the method is replaced with a setter but without a deprecated wrapper.

It may cause bug as below.

<img width="668" alt="01"  src="https://user-images.githubusercontent.com/14974790/31306604-2b4a2356-ab86-11e7-9f46-e55a5151d9d6.png">

Thanks you !

**Comment by MIKUScallion** [comment]
It may have another bug. When get length without check.

![02](https://user-images.githubusercontent.com/14974790/31386104-3dba4d8a-adf8-11e7-942b-d4620c41b792.jpg)

**Comment by lannymcnie** [comment]
@MIKUScallion Thanks, don't know how we missed that one!

The two issues don't seem related (even though they are in the same method)

**Comment by lannymcnie** [comment]
Regarding the second issue -- what are the circumstances that cause this? Although we aren't adequately checking for the error condition, it isn't clear how to reproduce that particular use-case. Can you post more info?

**Comment by MIKUScallion** [comment]
Haha, I will try to extract **use-case** demo about the second issue. &_&

**Comment by lannymcnie** [comment]
The second issue is documented here: https://github.com/CreateJS/SoundJS/issues/283

I am closing this one for now.

**Comment by k-may** [comment]
I don't understand how this is closed? I'm experiencing the first issue.

**Comment by lannymcnie** [comment]
@k-may What version are you using? This is just fixed in NEXT, the tagged version (1.0.2) does not contain the fix.

**Comment by k-may** [comment]
Okay, that explains it, I'm using the latest download, 1.0.0

**Comment by SyntaxErrorOnLine1** [comment]
@lannymcnie Could you tell me what you mean "fixed in NEXT"? I don't see a branch or tag with that name and NPM is still on 1.0.1. Could you tell me how I can get the fixed version? Or at least see the fix you applied (I can't seem to find any commit or pull request that correlates) so I can manually apply it myself? Any help would be really appreciated, thanks.
