### ISSUE TITLE
Contributing To Project

### ISSUE THREAD

**Issue by gngster** [CreateJS/SoundJS#286]
Hi I couldn't find a guide on how I can contribute to this project!

**Comment by lannymcnie** [comment]
We have never created guides - that is a good idea! 

In the mean time, we welcome pull requests on fixes, documentation updates, and even features. Ideally changes are discrete, documented inline with current standards, and don't contain superficial changes like tab formatting an entire file (hard to accept a PR that has 1000 changes). We also prefer don't contain the built docs/libs -- which we typically do once changes are integrated into the library.

Thanks!

**Comment by lannymcnie** [comment]
Leaving this open as a reminder to put together an official contribution guide.

**Comment by lannymcnie** [comment]
Closing this, as our 2.0 ES6 branch now contains this info. Thanks for the suggestion.
