### ISSUE TITLE
Source for swf?

### ISSUE THREAD

**Issue by 0x00A** [CreateJS/SoundJS#289]
Is there a repo or source code available for the [`swf`](https://github.com/CreateJS/SoundJS/blob/master/src/soundjs/flashaudio/FlashAudioPlugin.swf) file?

**Comment by lannymcnie** [comment]
Yes, the SWF source is in `/dev/com/createjs/soundjs`. The FLA that was initially provided was deprecated in favor of a grunt-based build process.

`grunt flash` or `grunt mxmlc` should build the SWF for you.

Cheers!
