### ISSUE TITLE
Is able Playing Sound/track with higher/lower frequence(Hz) by SoundJs

### ISSUE THREAD

**Issue by Cpin0312** [CreateJS/SoundJS#291]
I have making a matching game, and i wish to play a sound when matched.
i need to make this sound been higher tone(Hz) each gem was matched.
Example like
1 combo : sound with 1Hz
2 combos : sound with 2Hz
3 combos : sound with 3Hz
4 combos : sound with 4Hz

i have my own sound file and what i want to do is every time i play it, sound frequency(Hz) would been higher.Not generate a new sound. 

is i able to do like this with SoundJs?

**Comment by lannymcnie** [comment]
Are you talking about generating audio? SoundJS just deals with the playback of sound files.

**Comment by Cpin0312** [comment]
Thank for reply!
@lannymcnie 
sorry for miss explain about sound source.
i have my own sound file and what i want to do is every time i play it, sound frequency(Hz) would been higher.
Is SoundJs available to do like this?

**Comment by lannymcnie** [comment]
Currently SoundJS can not affect audio that way. You can access the WebAudioPlugin context, and work directly with it, but its not really optimized to do that. Check out the [WebAudio Node Insertion](https://github.com/CreateJS/SoundJS/blob/master/examples/07_WebAudioNodeInsertion.html) demo, which does some direct access, and might give you a place to start.

We are working on a new approach that will enable better WebAudio features, but its a ways out.

**Comment by Cpin0312** [comment]
@lannymcnie 
Thanks,I would try it later!!
