### ISSUE TITLE
Cant play on startup

### ISSUE THREAD

**Issue by Cpin0312** [CreateJS/SoundJS#292]
i have using soundjs when startup my game but it is not able to play.
but,when i can play the other sound when triggered by mouse event and other.
is it just a setting problem? html didnt show any error.

**Comment by lannymcnie** [comment]
WebAudio requires a user event to unlock the audio context on mobile devices. Until you cause that user event, audio will not play.

SoundJS listens for user events (specific touch events mainly) and unlocks the context for you. On mobile, it is a good idea to show some sort of "click to start" interaction. You don't have to do anything other than ensure that interaction happens before playing audio.
