### ISSUE TITLE
Phonegap example

### ISSUE THREAD

**Issue by FPeters84** [CreateJS/SoundJS#293]
Dear awesome people that might help me,

I am trying to make a very basic soundboard app by using Cordova Phonegap, and building my app in the cloud on Phonegap build.

To be honest, I am a bit of a noob and I am a bit lost in the documentation :)
Does somebody maybe has a working example of a phonegap app?
That would be awesome :)

Many thanks in advance for your consideration, and thank you!
Kind regards,
Frank

**Comment by lannymcnie** [comment]
We don't have any samples currently. The Cordova plugin is fairly out of date unfortunately. 

Do you have any specific questions? StackOverflow is a good place to post them. 
Cheers.
