### ISSUE TITLE
soundjs not working on new chrome 

### ISSUE THREAD

**Issue by s-senguttuvan** [CreateJS/SoundJS#299]
error traced in F12 - console

"The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page."

sound loaded using preloadjs and playing using soundjs.

in chrome suddenly shows this error, other browser working fine.

recent chrome browser not working

**Comment by s-senguttuvan** [comment]
what other?

**Comment by lannymcnie** [comment]
I assume @LokeshSomarla is asking which other browser it works.
> in chrome suddenly shows this error, other browser working fine.

**Comment by s-senguttuvan** [comment]
other it works

**Comment by lannymcnie** [comment]
Closing in favour of duplicate issue with more info #305

**Comment by Akurn** [comment]
#297 might be more applicable for this one, since this mentions AudioContext (WebAudioPlugin). 
As #305 is specifically HTMLAudioPlugin related.
