### ISSUE TITLE
WebAudioPlugin not registering correctly when running Chrome from local file

### ISSUE THREAD

**Issue by bbottema** [CreateJS/SoundJS#54]
Running the TestSuite.html test-app from the website works fine. It registers, detects and uses the WebAudioPlugin correctly.

Running the same TestSuit.html test-app from local harddisk (downloaded from github trunk) doesn't work and it reverts to the HTMLAudioPlugin (forcing the code to register only WebAudioPlugin doesn't work, resulting in a message that Chrome doesn't support SoundJs).

What gives?

**Comment by simongcc** [comment]
I have just meet the same problem and thanks for the information.
BTW, the https://xhr.spec.whatwg.org/ shows that 

```
Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user’s experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when current global object is a Window object. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an InvalidAccessError exception when it occurs.
```

so is this code needed to be changed back?
```
xhr.open("GET", "WebAudioPlugin.js", false);
```
=>
```
xhr.open("GET", "WebAudioPlugin.js");
```
