### ISSUE TITLE
DELIMITER = deprecated?

### ISSUE THREAD

**Issue by aholla** [CreateJS/SoundJS#78]
I see that the file path has been deprecated. Would it be possible to leave it in? Currently I store all my mp3 in one folder, wav's in another folder and ogg's in another folder. 

With the new 'alternateExtensions' I won't be able to do this and will have to mix/put all the files in one folder.

The alternative is I would have to detect which file type is the one that can be played and then do my own regex on the file path that is then passed into the manifest.

It's no big deal :)

**Comment by OJayRobinson** [comment]
SoundJS has added support for alternate file paths and extensionless files.
This is accomplished by passing an object for src that has various paths with property labels matching the extension.  These labels are how SoundJS determines if the browser will support the sound.  Priority is determined by the property order (first property is tried first).

Example
```javascript
var sounds = {path:"./audioPath/",
  manifest: [
  {id: "cool", src: {mp3:"mp3/awesome.mp3", ogg:"noExtensionOggFile"}}
]};
```

Note an id is required for playback and this is not supported with PreloadJS yet.

I'm curious what you all think.

**Comment by tomer78** [comment]
Actually it's not really a personal preference. Sometime it's a must to have separate folders for the sound files. For example,if you store your sounds on amazon s3 servers, then you get different file path for each file

**Comment by lannymcnie** [comment]
The new approach, documented above, is also designed to support CDN-based files, such as amazon.

Cheers.

**Comment by tomer78** [comment]
ok. great!thanks..

Date: Mon, 9 Mar 2015 06:45:01 -0700
